# Generated by Django 3.0.5 on 2021-01-13 01:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0002_auto_20210113_0112'),
        ('place', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='classes',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='classes.Classes'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='place',
            name='room',
            field=models.CharField(default=0, max_length=255, verbose_name='Room'),
            preserve_default=False,
        ),
    ]
